# Generated by Django 2.0.12 on 2019-12-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('base_price', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='orders.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='carttopping', to='orders.Topping'),
        ),
    ]
