# Generated by Django 2.0.12 on 2019-12-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191222_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=64)),
                ('base_price', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='orders.Item')),
                ('topping', models.ManyToManyField(blank=True, related_name='ordertopping', to='orders.Topping')),
            ],
        ),
    ]
